import type { Feature } from "../types/types";

export const features: Feature[] = [
  {
    name: "AI Visibility Tracker",
    slug: "ai-visibility-tracker",
    category: "Market Intelligence",
    status: "live",
    oneLiner: "Track how often your brand is mentioned and cited across ChatGPT, Perplexity, Gemini, Claude, Grok, and Copilot.",
    icon: "lucide:radar",
    iconClass: "bg-blue-500/10 text-blue-400",
  },
  {
    name: "Industry Metrics",
    slug: "industry-metrics",
    category: "Market Intelligence",
    status: "live",
    oneLiner: "Benchmark your AI visibility against industry averages and see where you stand in your category.",
    icon: "lucide:bar-chart-3",
    iconClass: "bg-purple-500/10 text-purple-400",
  },
  {
    name: "Community Manager",
    slug: "community-manager",
    category: "Market Intelligence",
    status: "live",
    oneLiner: "Scan Reddit for brand mentions, category conversations, and competitor comparisons in real time.",
    icon: "lucide:messages-square",
    iconClass: "bg-pink-500/10 text-pink-400",
  },
  {
    name: "Agentic Customer Journey & CRM Brain",
    slug: "agentic-crm",
    category: "Market Intelligence",
    status: "coming-soon",
    oneLiner: "Map how AI-driven customer journeys reference your brand at every touchpoint.",
    icon: "lucide:brain-circuit",
    iconClass: "bg-indigo-500/10 text-indigo-400",
  },
  {
    name: "Hyper-Personalised Engines",
    slug: "hyper-personalized-engines",
    category: "Content Production",
    status: "coming-soon",
    oneLiner: "Generate content variations optimised for how each AI engine structures its answers.",
    icon: "lucide:sparkles",
    iconClass: "bg-amber-500/10 text-amber-400",
  },
  {
    name: "AI-Native Content & Creative Production",
    slug: "content-creative-production",
    category: "Content Production",
    status: "coming-soon",
    oneLiner: "Produce AI-citation-ready content — articles, briefs, and creatives designed to be picked up by LLMs.",
    icon: "lucide:pen-tool",
    iconClass: "bg-teal-500/10 text-teal-400",
  },
  {
    name: "Trend Prediction",
    slug: "trend-prediction",
    category: "Prediction",
    status: "coming-soon",
    oneLiner: "Forecast emerging topics and queries before they trend inside AI search engines.",
    icon: "lucide:trending-up",
    iconClass: "bg-orange-500/10 text-orange-400",
  },
  {
    name: "Content Performance Prediction",
    slug: "content-performance-prediction",
    category: "Prediction",
    status: "coming-soon",
    oneLiner: "Predict how likely a piece of content is to be cited by AI engines before you publish.",
    icon: "lucide:gauge",
    iconClass: "bg-cyan-500/10 text-cyan-400",
  },
  {
    name: "Influencer Vetting & Fraud Detection",
    slug: "influencer-vetting",
    category: "Prediction",
    status: "coming-soon",
    oneLiner: "Evaluate influencer credibility and detect engagement fraud using AI-powered signals.",
    icon: "lucide:shield-check",
    iconClass: "bg-emerald-500/10 text-emerald-400",
  },
  {
    name: "Predictive Journey & Budget Optimisation",
    slug: "budget-optimization",
    category: "Prediction",
    status: "coming-soon",
    oneLiner: "Allocate marketing spend based on predicted AI visibility ROI across channels.",
    icon: "lucide:calculator",
    iconClass: "bg-rose-500/10 text-rose-400",
  },
];
