import type { UseCase } from "../types/types";

export const useCases: UseCase[] = [
  { title: "Real Estate", slug: "real-estate", industry: "Real Estate", description: "Help property developers and brokerages become the brand AI recommends when buyers ask 'best real estate agents near me'.", icon: "lucide:building-2", iconClass: "bg-blue-500/10 text-blue-400" },
  { title: "E-commerce & Retail", slug: "ecommerce-retail", industry: "E-commerce & Retail", description: "Ensure your client's products surface when shoppers ask AI for buying recommendations and product comparisons.", icon: "lucide:shopping-cart", iconClass: "bg-orange-500/10 text-orange-400" },
  { title: "Fintech & Banking", slug: "fintech-banking", industry: "Fintech & Banking", description: "Track whether AI engines cite your client's financial products or route users to competitors.", icon: "lucide:landmark", iconClass: "bg-emerald-500/10 text-emerald-400" },
  { title: "Healthcare & Pharma", slug: "healthcare-pharma", industry: "Healthcare & Pharma", description: "Monitor how AI surfaces health brands, clinics, and pharmaceutical products in patient-facing queries.", icon: "lucide:heart-pulse", iconClass: "bg-red-500/10 text-red-400" },
  { title: "SaaS & Software", slug: "saas-software", industry: "SaaS & Software", description: "Discover whether AI recommends your client's tool or sends prospects to G2 listings and competitor pages.", icon: "lucide:cloud", iconClass: "bg-sky-500/10 text-sky-400" },
  { title: "Education & EdTech", slug: "education-edtech", industry: "Education & EdTech", description: "Track how AI answers queries about courses, universities, and learning platforms for your education clients.", icon: "lucide:graduation-cap", iconClass: "bg-violet-500/10 text-violet-400" },
  { title: "Travel & Hospitality", slug: "travel-hospitality", industry: "Travel & Hospitality", description: "Monitor AI recommendations for hotels, destinations, and travel services when users plan trips via chatbots.", icon: "lucide:plane", iconClass: "bg-cyan-500/10 text-cyan-400" },
  { title: "Automotive", slug: "automotive", industry: "Automotive", description: "Track whether AI cites your client's brand when users ask about cars, EVs, dealerships, and vehicle comparisons.", icon: "lucide:car", iconClass: "bg-zinc-500/10 text-zinc-400" },
  { title: "Insurance", slug: "insurance", industry: "Insurance", description: "See which insurance providers AI recommends and ensure your client's policies are part of the conversation.", icon: "lucide:shield", iconClass: "bg-indigo-500/10 text-indigo-400" },
  { title: "Legal Services", slug: "legal-services", industry: "Legal Services", description: "Monitor how AI handles legal queries and whether your client's law firm or legal platform gets cited.", icon: "lucide:scale", iconClass: "bg-amber-500/10 text-amber-400" },
  { title: "Food & Beverage", slug: "food-beverage", industry: "Food & Beverage", description: "Track AI mentions for restaurant chains, FMCG brands, and D2C food brands across AI search engines.", icon: "lucide:utensils", iconClass: "bg-yellow-500/10 text-yellow-400" },
  { title: "Fashion & Apparel", slug: "fashion-apparel", industry: "Fashion & Apparel", description: "Ensure your fashion client's brand surfaces in AI-powered styling advice, product lookups, and trend queries.", icon: "lucide:shirt", iconClass: "bg-pink-500/10 text-pink-400" },
  { title: "Home Appliances & Electronics", slug: "home-appliances-electronics", industry: "Home Appliances & Electronics", description: "Track whether AI recommends your client's appliances when users ask for the best AC, washing machine, or inverter.", icon: "lucide:refrigerator", iconClass: "bg-teal-500/10 text-teal-400" },
  { title: "Fitness & Wellness", slug: "fitness-wellness", industry: "Fitness & Wellness", description: "Monitor AI visibility for gyms, supplements, wellness apps, and health brands across all major AI engines.", icon: "lucide:dumbbell", iconClass: "bg-lime-500/10 text-lime-400" },
  { title: "Media & Entertainment", slug: "media-entertainment", industry: "Media & Entertainment", description: "Track how AI engines reference streaming platforms, production houses, and media brands in entertainment queries.", icon: "lucide:clapperboard", iconClass: "bg-fuchsia-500/10 text-fuchsia-400" },
  { title: "Logistics & Supply Chain", slug: "logistics-supply-chain", industry: "Logistics & Supply Chain", description: "See whether AI recommends your client's logistics services when businesses search for shipping and fulfilment partners.", icon: "lucide:truck", iconClass: "bg-stone-500/10 text-stone-400" },
  { title: "HR & Recruitment", slug: "hr-recruitment", industry: "HR & Recruitment", description: "Monitor how AI surfaces job boards, HR tools, and staffing agencies when users ask about hiring and careers.", icon: "lucide:users", iconClass: "bg-purple-500/10 text-purple-400" },
  { title: "Agriculture & AgriTech", slug: "agriculture-agritech", industry: "Agriculture & AgriTech", description: "Track AI recommendations for agricultural products, farm tech tools, and agri-commerce platforms.", icon: "lucide:sprout", iconClass: "bg-green-500/10 text-green-400" },
  { title: "Telecom", slug: "telecom", industry: "Telecom", description: "Monitor which telecom providers AI recommends for plans, broadband, and mobile services in your client's market.", icon: "lucide:signal", iconClass: "bg-blue-600/10 text-blue-500" },
  { title: "Energy & Utilities", slug: "energy-utilities", industry: "Energy & Utilities", description: "Track AI visibility for solar companies, energy providers, and utility brands across AI-driven search.", icon: "lucide:zap", iconClass: "bg-yellow-600/10 text-yellow-500" },
];
